import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import WagmiContextWrapper from "../context/WagmiContextWrapper";
import { cookieToInitialState } from "wagmi";
import { config } from "../context/WagmiContextWrapper/config";
import { headers } from "next/headers";
import ReactQueryWrapper from "../context/ReactQueryWrapper";
import "@/scss/global.scss";
import AntdThemeWrapper from "@/context/AntdTheme";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-family",
  weight: ["400", "500", "600", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.variable}>
        <AntdRegistry>
          <AntdThemeWrapper>
            <WagmiContextWrapper initialState={initialState}>
              <ReactQueryWrapper>{children}</ReactQueryWrapper>
            </WagmiContextWrapper>
          </AntdThemeWrapper>
        </AntdRegistry>
      </body>
    </html>
  );
}
